spring:
  application:
    name: assignment-management-system
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/ams
    username: ams
    password: ams
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  #  liquibase:
  #    enabled: true
  #    change-log: classpath:/db/liquibase/changelog-master.xml
  cache:
    jcache:
      config: classpath:/config/ehcache.xml
  sql:
    init:
      platform: mysql

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failureRateThreshold: 50
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 10
#        waitDurationInOpenState: 20s
#        permittedNumberOfCallsInHalfOpenState: 2
#        registerHealthIndicator: true
